name: channelprototype_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.11.17=hbcca054_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hdb19cb5_0
  - cryptography=41.0.3=py311hdda0065_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=pyhd33586a_0
  - ipython=8.20.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py311h38be061_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib=3.8.0=py311h06a4308_0
  - matplotlib-base=3.8.0=py311ha02d727_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.1=py311h06a4308_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - ply=3.11=py311h06a4308_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.1.1=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=25.1.0=py311h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - scipy=1.11.4=py311h08b1b3b_0
  - setuptools=68.0.0=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.16.1=py311_cpu
  - tornado=6.3.3=py311h5eee18b_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - urllib3=1.26.18=py311h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aenum==3.1.15
      - affine==2.4.0
      - aioboto3==13.4.0
      - aiobotocore==2.18.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - attrs==25.1.0
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.45.5
      - bokeh==3.6.3
      - boto3==1.36.1
      - botocore==1.36.1
      - cartopy==0.23.0
      - cftime==1.6.3
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - dask==2024.5.1
      - deeplake==3.9.38
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - efficientnet-pytorch==0.7.1
      - fiona==1.10.1
      - frozenlist==1.5.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.10.0
      - hub==3.0.1
      - huggingface-hub==0.30.1
      - humbug==0.3.2
      - hydra-core==1.3.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonargparse==4.38.0
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - libdeeplake==0.0.157
      - lightly==1.5.19
      - lightly-utils==0.0.2
      - lightning==2.5.1
      - lightning-utilities==0.14.3
      - llvmlite==0.41.1
      - locket==1.0.0
      - lz4==4.4.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - moviepy==2.1.2
      - multidict==6.1.0
      - multiprocess==0.70.17
      - munch==4.0.0
      - narwhals==1.29.0
      - netcdf4==1.6.5
      - numba==0.58.1
      - omegaconf==2.3.0
      - pandas==2.1.4
      - partd==1.4.2
      - pathos==0.3.3
      - plotly==6.0.0
      - pox==0.3.5
      - ppft==1.7.6.9
      - pretrainedmodels==0.7.4
      - proglog==0.1.10
      - propcache==0.2.1
      - pyjwt==2.10.1
      - pyproj==3.6.1
      - pyshp==2.3.1
      - python-dotenv==1.0.1
      - pytorch-lightning==2.5.1
      - pytorch-model-summary==0.1.2
      - pytz==2023.3.post1
      - rasterio==1.4.3
      - rdkit==2024.9.5
      - rtree==1.4.0
      - s3transfer==0.11.2
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scikit-learn-extra==0.3.0
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.4.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shap==0.44.0
      - shapely==2.0.4
      - slicer==0.0.7
      - smmap==5.0.2
      - soundfile==0.13.1
      - soupsieve==2.5
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - timm==1.0.15
      - toolz==0.12.1
      - torchgeo==0.7.0
      - torchmetrics==1.7.1
      - tqdm==4.66.1
      - typeshed-client==2.7.0
      - tzdata==2023.3
      - wandb==0.19.7
      - wrapt==1.17.2
      - xarray==2024.5.0
      - xyzservices==2025.1.0
      - yarl==1.18.3
prefix: /users/.conda/envs/channelprototype_env
